basePath: /
host: 127.0.0.1:8080
info:
  contact:
    email: bitop@spatecon.ru
    name: API Support
    url: https://vk.com/bmstu_schedule
  description: Bmstu Open IT Platform
  license:
    name: AS IS (NO WARRANTY)
  title: BITOP API
  version: "1.0"
paths: {}
swagger: "2.0"
